name: Build Docker Image

on:
    push:
        branches:
            ["main"]
jobs:
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up Docker
              uses: docker/setup-buildx-action@v3
            
            - name: Build Docker image
              run: docker build -t my-app:latest

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: jubairthematics/harshcicd:latest
